<?php if (Session::isConnected() && $_SESSION['auth']['role']) : ?>
    <h2 class="title-content">Ajouter un article</h2>
    <form method="post" action="add_post.php">
        <label for="title">Titre
            <input type="text" name="title" id="title" value="" />
        </label>
        <label for="content">Message
            <textarea name="content" id="content" rows="10" cols="7" class="textarea-field" required></textarea>
        </label>
        <div>
            <input type="submit" value="Envoyer">
            <a href="dashboard.php" class="cancel-btn">Annuler</a>
        </div>
    </form>
<?php endif; ?>