<div class="form_center">
    <form action="login.php" method="post">
        <h2>Connexion</h2>
        <label for="mail">E-mail</label>
        <input type="text" name="mail" placeholder="Votre adresse e-mail" id="mail">

        <label for="password">Mot de passe</label>
        <input type="password" name="password" placeholder="Votre mot de passe" id="password">
        <div>
            <input type="submit" value="Connexion">
        </div>
        <p>Pas encore inscrit ? Inscrivez-vous
            <a href="register.php" class="nav-icon"><span class="register-link">ICI</span></a>
        </p>
    </form>
</div>